#!/usr/bin/env bash
set -euo pipefail

export HOST="127.0.0.1"
export PORT="8931"
export WRAPPER_ALLOWED_ROOTS="${WRAPPER_ALLOWED_ROOTS:-$HOME/Desktop}"
export WRAPPER_MAX_OUTPUT_BYTES="${WRAPPER_MAX_OUTPUT_BYTES:-200000}"
export WRAPPER_DEFAULT_TIMEOUT_SECONDS="${WRAPPER_DEFAULT_TIMEOUT_SECONDS:-30}"

npm start
